### ISSUE TITLE
Реализовать функционал подсчета кол-ва смс за текущий день

### ISSUE THREAD

**Issue by kirush0280** [rasskazovaleksey/kannel_api_wrapper#1]
Для скормления заббиксу необходимо реализовать функционал, чтобы:
можно было написать скриптик (например php script.php sent):
выдал цифру на основании колва отправленных смс за текущий день.
Предусмотреть помимо sent, delivered и failed.

**Comment by rasskazovaleksey** [comment]
производится по средствам поиска(search) например GET 
http://localhost:12999/api/smses/search/findByCreatedAndStatus?start=2017-08-15T00:00&end=2017-08-15T23:59:59&status=ACCEPTED
